/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Win32RegKey */

#ifndef _Included_Win32RegKey
#define _Included_Win32RegKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Win32RegKey
 * Method:    getValue
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_Win32RegKey_getValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Win32RegKey
 * Method:    setValue
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_Win32RegKey_setValue
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
