/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class Printf4 */

#ifndef _Included_Printf4
#define _Included_Printf4

#pragma pack(4)

typedef struct ClassPrintf4 {
    char PAD;	/* ANSI C requires structures to have a least one member */
} ClassPrintf4;
HandleTo(Printf4);

#pragma pack()

#ifdef __cplusplus
extern "C" {
#endif
struct Hjava_io_PrintWriter;
struct Hjava_lang_String;
extern void Printf4_fprint(struct HPrintf4 *,struct Hjava_io_PrintWriter *,struct Hjava_lang_String *,double);
#ifdef __cplusplus
}
#endif
#endif
